BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-bt"
BBFILE_PRIORITY_qti-bt = "12"
BBFILE_PATTERN_qti-bt := "^${LAYERDIR}/"

LAYERSERIES_COMPAT_qti-bt = "dunfell scarthgap"

BBFILES += "${LAYERDIR}/recipes/*/*.bb \
            ${LAYERDIR}/recipes/*/*.bbappend"
