BBFILES += "${LAYERDIR}/recipes/*/*.bb ${LAYERDIR}/recipes/*/*.bbappend ${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-products/images/*.bbappend"
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-bt"
BBFILE_PRIORITY_qti-bt = "12"
BBFILE_PATTERN_qti-bt := "^${LAYERDIR}/"
PREFERRED_VERSION_btpower-dlkm = "${@bb.utils.contains('LAYERSERIES_COMPAT_core', 'dunfell', '2.0', '1.0', d)}"
LAYERSERIES_COMPAT_qti-bt = "dunfell kirkstone"
