#! /bin/sh
# Copyright (c) 2020-2021, The Linux Foundation. All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Changes from Qualcomm Technologies, Inc. are provided under the following license:
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear


set -e

 BLUETOOTHPOWER_KERNEL_MODULE_PATH=/lib/modules/$(uname -r)/btpower.ko
 BLUETOOTH_FM_SLIM_KERNEL_MODULE_PATH=/lib/modules/$(uname -r)/bt_fm_slim.ko
 BLUETOOTHFMCODEC_KERNEL_MODULE_PATH=/lib/modules/$(uname -r)/btfmcodec.ko
 BLUETOOTH_FM_SWR_KERNEL_MODULE_PATH=/lib/modules/$(uname -r)/bt_fm_swr.ko
 BLUETOOTHFM_SLIM_CODEC_KERNEL_MODULE_PATH=/lib/modules/$(uname -r)/btfm_slim_codec.ko

case "$1" in
  start)
  if [ -e /sys/bus/platform/drivers/btpower ]; then
	echo "btpower has already resided in kernel."
  elif [ -e ${BLUETOOTHPOWER_KERNEL_MODULE_PATH} ]; then
	insmod ${BLUETOOTHPOWER_KERNEL_MODULE_PATH}
	echo "insmod kernel btpower.ko Done"
  else
    echo "exit due to no btpower.ko"
  fi
  if [ -e /sys/bus/platform/drivers/bt_fm_slim ]; then
	echo "bt_fm_slim has already resided in kernel."
  elif [ -e ${BLUETOOTH_FM_SLIM_KERNEL_MODULE_PATH} ]; then
	insmod ${BLUETOOTH_FM_SLIM_KERNEL_MODULE_PATH}
	echo "insmod kernel bt_fm_slim.ko Done"
  else
    echo "exit due to no bt_fm_slim.ko"
  fi
  if [ -e /sys/bus/platform/drivers/btfmcodec ]; then
	echo "btfmcodec has already resided in kernel."
  elif [ -e ${BLUETOOTHFMCODEC_KERNEL_MODULE_PATH} ]; then
	insmod ${BLUETOOTHFMCODEC_KERNEL_MODULE_PATH}
	echo "insmod kernel btfmcodec.ko Done"
  else
    echo "exit due to no btfmcodec.ko"
  fi
  if [ -e /sys/bus/platform/drivers/bt_fm_swr ]; then
	echo "bt_fm_swr has already resided in kernel."
  elif [ -e ${BLUETOOTH_FM_SWR_KERNEL_MODULE_PATH} ]; then
	insmod ${BLUETOOTH_FM_SWR_KERNEL_MODULE_PATH}
	echo "insmod kernel bt_fm_swr.ko Done"
  else
    echo "exit due to no bt_fm_swr.ko"
  fi
  if [ -e /sys/bus/platform/drivers/btfm_slim_codec ]; then
	echo "btfm_slim_codec has already resided in kernel."
  elif [ -e ${BLUETOOTHFM_SLIM_CODEC_KERNEL_MODULE_PATH} ]; then
	insmod ${BLUETOOTHFM_SLIM_CODEC_KERNEL_MODULE_PATH}
	echo "insmod kernel btfm_slim_codec.ko Done"
  else
    echo "exit due to no btfm_slim_codec.ko"
  fi

  # correct SELinux labels on all /dev/bt* nodes
  if [ -x /sbin/restorecon ]; then
      for node in /dev/bt*; do
          [ -e "$node" ] && /sbin/restorecon "$node"
      done
  fi
  exit 0
  ;;

  stop|restart|reload|force-reload)
  echo "Action '$1' is meaningless for $0"
  exit 0
  ;;

  *)
  echo "Usage: $0 start"
  exit 1
esac



