#!/bin/sh /etc/rc.common

#Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

START=78
STOP=71

USE_PROCD=1
PROCD_DEBUG=1

MY_PROG=/usr/bin/btproperty

start_service() {
	if [ ! -d /data/misc/bluetooth ]; then
		mkdir -p /data/misc/bluetooth
		chown qbt:root /data/misc/bluetooth
		chmod 0775 /data/misc/bluetooth
	fi
	procd_open_instance
		procd_set_param command ${MY_PROG}
		[ -x /sbin/ujail -a -e /etc/capabilities/bt-property.json ] && {
			procd_add_jail bt-property
			procd_set_param capabilities /etc/capabilities/bt-property.json
			#procd_add_jail_mount_rw /data/misc/bluetooth/
		}
		procd_set_param user qbt
		procd_set_param group qbt
#		procd_set_param respawn 900 5 3
#		procd_set_param stdout 1
#		procd_set_param stderr 1
		procd_set_param no_new_privs 1
	procd_close_instance
}

stop_service() {
	echo "Stopping bt-property"
	service_stop ${MY_PROG}
}
